name: Build Dependencies list

on:
  workflow_dispatch:
    inputs:
      repo-names:
        description: "Comma separated list of repos to scan."
        required: true
        default: ""
      depth:
        description: "The depth of transitive dependencies to report on."
        required: true
        default: "0"

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    name: Genereate a list of dependencies for this repository
    steps:
      - name: Generate dependencies action
        uses: thedave42/generate-dependencies-csv-action@v5
        with:
          repo-token: ${{ github.token }}  # This token must have read access to scan a repo, to scan other repos use a Action secret to define a token with broader access.
          repo-names: ${{ github.event.inputs.repo-names }}
          depth: ${{ github.event.inputs.depth }}
